-- Tabela de Pacientes
CREATE TABLE patients (
id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
num TEXT,
nome TEXT,
prontuario TEXT,
sexo TEXT,
idade_primeira_consulta TEXT,
municipio TEXT,
estado_civil TEXT,
num_filhos TEXT,
ocupacao TEXT,
escolaridade TEXT,
cuidador_pos_op TEXT,
data_primeira_consulta TEXT,
data_emissao_aih TEXT,
tempo_protocolo TEXT,
data_cirurgia TEXT,
idade_na_cirurgia TEXT,
tipo_cirurgia TEXT,
peso_inicial TEXT,
peso_ultimo_pre_op TEXT,
variacao_peso_pre_op TEXT,
altura TEXT,
imc_inicial TEXT,
imc_ultimo_pre_op TEXT,
expectativa_peso TEXT,
perda_esperada TEXT,
tabagismo TEXT,
etilismo TEXT,
atividade_fisica_pre TEXT,
comer_emocional TEXT,
autoavaliacao_psicologica TEXT,
obesidade_desde TEXT,
tentativas_emagrecimento TEXT,
cirurgias_previas TEXT,
has TEXT,
dm2 TEXT,
dislipidemia TEXT,
esteatose_hepatica TEXT,
colelitiase_pre TEXT,
asma TEXT,
outras_comorbidades TEXT,
medicacoes_em_uso TEXT,
h_pylori_resultado TEXT,
h_pylori_situacao TEXT,
eda_resultado TEXT,
fez_colonoscopia TEXT,
resultado_colonoscopia TEXT,
outras_alteracoes_gi TEXT,
usg_abdome TEXT,
espirometria_resultado TEXT,
rx_torax TEXT,
eco_fe TEXT,
eco_psap TEXT,
eco_outras_alteracoes TEXT,
risco_pulmonar TEXT,
risco_cv TEXT,
clexane_dose TEXT,
hba1c TEXT,
glicemia_jejum TEXT,
tsh TEXT,
t4_livre TEXT,
b12 TEXT,
vitamina_d TEXT,
colesterol_total TEXT,
hdl TEXT,
ldl TEXT,
triglicerideos TEXT,
tgo TEXT,
tgp TEXT,
peso_po_9dias TEXT,
peso_po_40dias TEXT,
peso_po_4_5meses TEXT,
peso_po_5meses TEXT,
peso_po_7meses TEXT,
peso_po_11meses TEXT,
peso_1ano_po TEXT,
perda_absoluta_1ano TEXT,
percent_excesso_peso_perdido TEXT,
atividade_fisica_1ano_po TEXT,
excesso_pele TEXT,
complicacoes_po TEXT,
adesao_suplementacao TEXT,
alta_cb TEXT,
observacoes_clinicas TEXT,
ultimo_imc TEXT,
-- Novos campos Pós-operatórios
eda_pos_data TEXT,
eda_pos_urease TEXT,
eda_pos_hpylori TEXT,
eda_pos_achados TEXT,
usg_pos_data TEXT,
usg_pos_vesicula TEXT,
usg_pos_observacoes TEXT,
last_edited_at TIMESTAMPTZ DEFAULT now(),
created_at TIMESTAMPTZ DEFAULT now()
);

-- Habilitar RLS (opcional, mas recomendado)
ALTER TABLE patients ENABLE ROW LEVEL SECURITY;

-- Criar política de acesso público (para simplificar o teste inicial)
CREATE POLICY "Permitir acesso público" ON patients FOR ALL USING (true);
